- name: Create project directory
  file:
    path: /opt/simple-app
    state: directory

- name: Copy app
  copy:
    src: "{{ playbook_dir }}/../app"
    dest: /opt/simple-app/

- name: Copy Dockerfile
  copy:
    src: "{{ playbook_dir }}/../Dockerfile"
    dest: /opt/simple-app/

- name: Copy docker-compose.yml
  copy:
    src: "{{ playbook_dir }}/../docker-compose.yml"
    dest: /opt/simple-app/

- name: Start application
  shell: docker-compose up -d 
  args:
    chdir: /opt/simple-app 